# Generated by Django 5.1.7 on 2025-03-26 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_metadata_post_post_type_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_type',
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.user'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
